-- Barasa Michael Murunga - BICS 1.2C - 150374 - 25-02-2023
-- FILE DESCRIPTION: Creates all Tables in the Database IF DON'T EXIST

CREATE TABLE IF NOT EXISTS tbl_Role (
  roleId INT NOT NULL AUTO_INCREMENT,
  title VARCHAR(255) NOT NULL,
  description VARCHAR(255) NOT NULL,
  permissions INT DEFAULT 0,
  dateCreated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  lastUpdated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (roleId)
);

CREATE TABLE IF NOT EXISTS tbl_Item (
  itemId INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  dateCreated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  lastUpdated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (itemId)
);

CREATE TABLE IF NOT EXISTS tbl_Customer (
  customerId INT NOT NULL AUTO_INCREMENT,
  firstName VARCHAR(255) NOT NULL,
  lastName VARCHAR(255) NOT NULL,
  middleName VARCHAR(255),
  gender VARCHAR(127) NOT NULL,
  emailAddress VARCHAR(255) NOT NULL,
  phoneNumber VARCHAR(255) NOT NULL,
  active BOOLEAN DEFAULT true,
  locationAddress TEXT NOT NULL,
  passcode VARCHAR(255) DEFAULT 'password' NOT NULL,
  dateCreated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  lastUpdated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (customerId)
);

CREATE TABLE IF NOT EXISTS tbl_Supplier (
  supplierId INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  specialty VARCHAR(255) NOT NULL,
  emailAddress VARCHAR(255) NOT  NULL,
  phoneNumber VARCHAR(255) NOT NULL,
  locationAddress TEXT NOT NULL,
  active BOOLEAN DEFAULT true,
  passcode VARCHAR(255) NOT NULL,
  dateCreated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  lastUpdated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (supplierId)
);

CREATE TABLE IF NOT EXISTS tbl_User (
  userId INT NOT NULL AUTO_INCREMENT,
  firstName VARCHAR(255) NOT NULL,
  lastName VARCHAR(255) NOT NULL,
  middleName VARCHAR(255),
  gender VARCHAR(127) NOT NULL,
  emailAddress VARCHAR(255) NOT NULL,
  phoneNumber VARCHAR(255) NOT NULL,
  nationalID VARCHAR(127) NOT NULL,
  locationAddress VARCHAR(255),
  active BOOLEAN DEFAULT true,
  passcode VARCHAR(255) NOT NULL,
  roleId INT NOT NULL,
  dateCreated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  lastUpdated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (roleId) REFERENCES tbl_Role(roleId),
  PRIMARY KEY (userId)
);

CREATE TABLE IF NOT EXISTS tbl_ItemInstance (
  itemInstanceId INT NOT NULL AUTO_INCREMENT,
  buyingPrice DECIMAL(10,2) NOT NULL,
  sellingPrice DECIMAL(10,2) NOT NULL,
  quantity INT NOT NULL,
  present BOOLEAN DEFAULT true,
  itemId INT NOT NULL,
  supplyId INT NOT NULL,
  dateCreated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  lastUpdated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (itemId) REFERENCES tbl_Item(itemId),
  FOREIGN KEY (supplyId) REFERENCES tbl_Supply(supplyId),
  PRIMARY KEY (itemInstanceId)
);

CREATE TABLE IF NOT EXISTS tbl_Order (
  orderId INT NOT NULL AUTO_INCREMENT,
  payment VARCHAR(127) NOT NULL,
  completed BOOLEAN DEFAULT false,
  customerId INT NOT NULL,
  dateCreated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  lastUpdated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (customerId) REFERENCES tbl_Customer(customerId),
  PRIMARY KEY (orderId)
);

CREATE TABLE IF NOT EXISTS tbl_Supply (
  supplyId INT NOT NULL AUTO_INCREMENT,
  payment VARCHAR(127) NOT NULL,
  completed BOOLEAN DEFAULT false,
  supplierId INT NOT NULL,
  dateCreated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  lastUpdated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (supplierId) REFERENCES tbl_Supplier(supplierId),
  PRIMARY KEY (supplyId)
);

CREATE TABLE IF NOT EXISTS tbl_OrderAssignment (
  orderAssignmentId INT NOT NULL AUTO_INCREMENT,
  quantity INT NOT NULL,
  orderId INT NOT NULL,
  itemInstanceId INT NOT NULL,
  dateCreated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  lastUpdated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (orderId) REFERENCES tbl_Order(orderId),
  FOREIGN KEY (itemInstanceId) REFERENCES tbl_ItemInstance(itemInstanceId),
  PRIMARY KEY (orderAssignmentId)
);
